apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::449078766873:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1S3KX8D71J9ZA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::449078766873:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-01T23:53:31Z"
  # managedFields:
  # - apiVersion: v1
  #   fieldsType: FieldsV1
  #   fieldsV1:
  #     f:data:
  #       .: {}
  #       f:mapRoles: {}
  #       f:mapUsers: {}
  #   manager: eksctl.exe
  #   operation: Update
  #   time: "2021-04-01T23:53:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1448"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0a55f05e-6144-441e-838b-652d8dfe7a00
